-- Add missing price columns to public.towns table to support town prices sync
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_30_Residential" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_30_Commercial" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_40_Residential" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_40_Commercial" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_50_Residential" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_50_Commercial" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_60_Residential" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_60_Commercial" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_80_Residential" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_80_Commercial" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Custom_Name" TEXT DEFAULT '';
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Custom_Residential" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Custom_Commercial" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_30" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_40" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_50" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_60" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Road_80" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Custom_Price" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Residential_Plot_Price" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Commercial_Plot_Price" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Residential_Shop_Price" NUMERIC DEFAULT 0;
ALTER TABLE public.towns ADD COLUMN IF NOT EXISTS "Commercial_Shop_Price" NUMERIC DEFAULT 0;

NOTIFY pgrst, 'reload schema';
